package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.controller.LicenciaController;
import ec.edu.sistemalicencias.dto.ReporteUsuarioDTO;
import ec.edu.sistemalicencias.model.exceptions.LicenciaException;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/*
 * Vista para generar reporte de todos los usuarios registrados en el sistema
 * Permite generar un docuemento que muestra al usuario, fecha_registro, emitido o no emitido la licencia.
 * */
public class GenerarReporteView extends JFrame {
    private JButton btnGoBack;
    private JComboBox<String> cmbFilterUsers;
    private JPanel PanelMainReport;
    private JLabel lblDescription;
    private JTable tblUsers;
    private JLabel lblViewUsers;
    private JScrollPane scrollTableUsers;
    private JPanel panelButtons;
    private JPanel panelFilter;

    private final LicenciaController controller;
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private DefaultTableModel modeloTabla;
    private List<ReporteUsuarioDTO> listaCompletaUsuarios;

    public GenerarReporteView(LicenciaController controller) {
        this.controller = controller;
        setTitle("Reporte de usuarios");
        setContentPane(PanelMainReport);
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        iniciarTabla();
        inicializarDatos();
        configurarEventos();

        setVisible(true);

    }

    private void inicializarDatos() {
        cmbFilterUsers.removeAllItems();
        cmbFilterUsers.addItem("Todos");
        cmbFilterUsers.addItem("Emitido");
        cmbFilterUsers.addItem("No Emitido");
        cmbFilterUsers.addItem("Vencido");

        cargarDatosIniciales();
    }

    private void iniciarTabla() {
        String[] columnas = {"ID", "Cédula", "Nombres", "Apellidos", "Teléfono", "Fecha Registro", "Estado Licencia"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblUsers.setModel(modeloTabla);
        tblUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    private void configurarEventos() {
        //btnGeneratePDF.addActionListener();
        btnGoBack.addActionListener(e -> dispose());
        cmbFilterUsers.addActionListener(e -> {
            String filtroSeleccionado = (String) cmbFilterUsers.getSelectedItem();

            if (listaCompletaUsuarios == null) return;
            if ("Todos".equals(filtroSeleccionado)) {
                llenarTabla(listaCompletaUsuarios);
            } else {
                List<ReporteUsuarioDTO> filtrada = new ArrayList<>();
                for (ReporteUsuarioDTO u : listaCompletaUsuarios) {
                    if (u.getEstadoLicencia().equals(filtroSeleccionado)) {
                        filtrada.add(u);
                    }
                }
                llenarTabla(filtrada);
            }
        });
    }

    private void cargarDatosIniciales() {
        try {
            listaCompletaUsuarios = controller.obtenerReporte();
            llenarTabla(listaCompletaUsuarios);

        } catch (LicenciaException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void llenarTabla(List<ReporteUsuarioDTO> listaAMostrar) {
        modeloTabla.setRowCount(0);

        for (ReporteUsuarioDTO u : listaAMostrar) {
            Object[] fila = {
                    u.getId(),
                    u.getCedula(),
                    u.getNombres(),
                    u.getApellidos(),
                    u.getTelefono(),
                    (u.getFechaRegistro() != null) ? u.getFechaRegistro().format(dateFormatter) : "Sin fecha",
                    u.getEstadoLicencia()
            };
            modeloTabla.addRow(fila);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelMainReport = new JPanel();
        PanelMainReport.setLayout(new GridLayoutManager(3, 6, new Insets(0, 0, 0, 0), -1, -1));
        scrollTableUsers = new JScrollPane();
        PanelMainReport.add(scrollTableUsers, new GridConstraints(1, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollTableUsers.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Usuarios", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-2104859)));
        tblUsers = new JTable();
        scrollTableUsers.setViewportView(tblUsers);
        panelFilter = new JPanel();
        panelFilter.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        PanelMainReport.add(panelFilter, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panelFilter.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "REPORTE DE USUARIOS REGISTRADOS", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, -1, -1, panelFilter.getFont()), null));
        lblViewUsers = new JLabel();
        lblViewUsers.setText("Filtrar por:");
        panelFilter.add(lblViewUsers, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cmbFilterUsers = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Todos");
        defaultComboBoxModel1.addElement("Emitidos");
        defaultComboBoxModel1.addElement("No emitidos");
        defaultComboBoxModel1.addElement("Vencidos");
        cmbFilterUsers.setModel(defaultComboBoxModel1);
        panelFilter.add(cmbFilterUsers, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDescription = new JLabel();
        lblDescription.setText("label");
        panelFilter.add(lblDescription, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelFilter.add(spacer1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        panelButtons = new JPanel();
        panelButtons.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), 5, 5));
        PanelMainReport.add(panelButtons, new GridConstraints(2, 1, 1, 5, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGoBack = new JButton();
        btnGoBack.setText("Volver");
        panelButtons.add(btnGoBack, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(40, 20), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelMainReport;
    }

}

