package ec.edu.sistemalicencias.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import java.awt.Font;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;


public class LoginView extends JFrame {
    private JPanel PanelLogin;
    private JLabel lblIniciarSesion;
    private JComboBox comboBox1;
    private JLabel lblusuario;
    private JTextField txtcontrasenia;
    private JLabel lblcontrasenia;
    private JButton btnIngresar;
    private JLabel lblImagen_Login;
    private JLabel lblImagen;
    private JPanel PanelImage;


    public LoginView() {
        // Configuración básica de la ventana
        setTitle("Bienvenido - Sistema de Licencias de Conducir");
        setSize(600, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setContentPane(PanelLogin);

        ImageIcon icono = new ImageIcon(
                LoginView.class.getResource("/icons/ingreso.png")
        );

        Image img = icono.getImage().getScaledInstance(
                90, 90, Image.SCALE_SMOOTH
        );

        lblImagen_Login.setIcon(new ImageIcon(img));

// Ajustar Tamaño
        ImageIcon icon = new ImageIcon(
                LoginView.class.getResource("/icons/images.jpeg")
        );

        Image img2 = icon.getImage();

        Image imgEscalada = img2.getScaledInstance(
                300, 500,
                Image.SCALE_SMOOTH
        );

        lblImagen.setIcon(new ImageIcon(imgEscalada));


        btnIngresar.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblIniciarSesion.setFont(new Font("Roboto", Font.BOLD, 40));
        lblusuario.setFont(new Font("Roboto", Font.BOLD, 15));
        lblcontrasenia.setFont(new Font("Roboto", Font.BOLD, 15));
        lblIniciarSesion.setFont(new Font("Roboto", Font.BOLD, 15));
        btnIngresar.setFont(new Font("Roboto", Font.BOLD, 15));
        setResizable(false);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelLogin = new JPanel();
        PanelLogin.setLayout(new GridLayoutManager(8, 2, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        PanelLogin.add(spacer1, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Administrador");
        comboBox1.setModel(defaultComboBoxModel1);
        PanelLogin.add(comboBox1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblusuario = new JLabel();
        lblusuario.setText("Usuario");
        PanelLogin.add(lblusuario, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblcontrasenia = new JLabel();
        lblcontrasenia.setText("Contraseña");
        PanelLogin.add(lblcontrasenia, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtcontrasenia = new JTextField();
        PanelLogin.add(txtcontrasenia, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnIngresar = new JButton();
        btnIngresar.setText("Ingresar");
        PanelLogin.add(btnIngresar, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIniciarSesion = new JLabel();
        lblIniciarSesion.setText("Iniciar Sesión");
        PanelLogin.add(lblIniciarSesion, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblImagen_Login = new JLabel();
        lblImagen_Login.setIcon(new ImageIcon(getClass().getResource("/icons/ingreso.png")));
        lblImagen_Login.setText("");
        PanelLogin.add(lblImagen_Login, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblImagen = new JLabel();
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/icons/images.jpeg")));
        lblImagen.setText("");
        PanelLogin.add(lblImagen, new GridConstraints(0, 1, 8, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelLogin;
    }

}

