package ec.edu.sistemalicencias.view.crudView;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import ec.edu.sistemalicencias.controller.UsuariosController;
import ec.edu.sistemalicencias.model.entities.Usuarios;
import ec.edu.sistemalicencias.model.exceptions.UsuarioException;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class PanelCrearUsuarioView {
    private JTextField txtNombre;
    private JTextField txtProfesion;
    private JTextField txtTelefono;
    private JTextField txtDireccion;
    private JTextField txtApellido;
    private JTextField txtCedula;
    private JRadioButton rbtnAdministrador;
    private JRadioButton rbtnAnalista;
    private JTextField txtNombreUsuario;
    private JPasswordField txtContrasenia;
    private JButton btnCrear;
    private JPanel PanelDatos;
    private JPanel PanelRegistrar;
    private JLabel lblNombre;
    private JLabel lblApellido;
    private JLabel lblCedula;
    private JLabel lblProfesion;
    private JLabel lblTelefono;
    private JLabel lblDireccion;
    private JLabel lblNombreUsuario;
    private JLabel lblContrasenia;
    private JPanel PanelMain;

    private UsuariosController controller;
    private ButtonGroup grupoRoles;

    public PanelCrearUsuarioView(UsuariosController controller) {
        this.controller = controller;

        grupoRoles = new ButtonGroup();
        grupoRoles.add(rbtnAdministrador);
        grupoRoles.add(rbtnAnalista);

        btnCrear.addActionListener(e -> crearUsuario());
    }

    private void crearUsuario() {
        try {
            String rolSeleccionado;

            if (rbtnAdministrador.isSelected()) {
                rolSeleccionado = "Administrador";
            } else if (rbtnAnalista.isSelected()) {
                rolSeleccionado = "Analista";
            } else {
                JOptionPane.showMessageDialog(PanelMain,
                        "ERROR: Registre todos los campos para crear un usuario.\n" +
                                "RECUERDE: Debe de asignar un rol al usuario por crear.",
                        "Error",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Usuarios usuario = new Usuarios();
            usuario.setNombre(txtNombre.getText());
            usuario.setApellido(txtApellido.getText());
            usuario.setCedula(txtCedula.getText());
            usuario.setProfesion(txtProfesion.getText());
            usuario.setTelefono(txtTelefono.getText());
            usuario.setDireccion(txtDireccion.getText());
            usuario.setNombreUsuario(txtNombreUsuario.getText());
            usuario.setContrasenia(new String(txtContrasenia.getPassword()));
            usuario.setRol(rolSeleccionado);

            Long id = controller.registrarUsuario(usuario);
            JOptionPane.showMessageDialog(PanelMain,
                    "Usuario creado exitosamente con ID: " + id,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarCampos();
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(PanelMain,
                    ex.getMessage(),
                    "Error de Validación",
                    JOptionPane.WARNING_MESSAGE);
        } catch (UsuarioException ex) {
            JOptionPane.showMessageDialog(PanelMain,
                    ex.getMessage(),
                    "Error del Sistema",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(PanelMain,
                    "Error inesperado: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtProfesion.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtNombreUsuario.setText("");
        txtContrasenia.setText("");
        grupoRoles.clearSelection();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelMain = new JPanel();
        PanelMain.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        PanelDatos = new JPanel();
        PanelDatos.setLayout(new GridLayoutManager(3, 4, new Insets(20, 20, 20, 20), -1, -1));
        PanelMain.add(PanelDatos, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, true));
        PanelDatos.setBorder(BorderFactory.createTitledBorder(null, "Datos personales", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lblNombre = new JLabel();
        lblNombre.setText("Nombre:");
        PanelDatos.add(lblNombre, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblCedula = new JLabel();
        lblCedula.setText("Cédula:");
        PanelDatos.add(lblCedula, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblApellido = new JLabel();
        lblApellido.setText("Apellido:");
        PanelDatos.add(lblApellido, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTelefono = new JLabel();
        lblTelefono.setText("Teléfono:");
        PanelDatos.add(lblTelefono, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblProfesion = new JLabel();
        lblProfesion.setText("Profesión:");
        PanelDatos.add(lblProfesion, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDireccion = new JLabel();
        lblDireccion.setText("Dirección:");
        PanelDatos.add(lblDireccion, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombre = new JTextField();
        PanelDatos.add(txtNombre, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtProfesion = new JTextField();
        PanelDatos.add(txtProfesion, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtTelefono = new JTextField();
        PanelDatos.add(txtTelefono, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtDireccion = new JTextField();
        PanelDatos.add(txtDireccion, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtApellido = new JTextField();
        PanelDatos.add(txtApellido, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtCedula = new JTextField();
        PanelDatos.add(txtCedula, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        PanelRegistrar = new JPanel();
        PanelRegistrar.setLayout(new GridLayoutManager(3, 3, new Insets(20, 20, 20, 20), -1, -1));
        PanelMain.add(PanelRegistrar, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, true));
        PanelRegistrar.setBorder(BorderFactory.createTitledBorder(null, "Registrar usuario", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        lblNombreUsuario = new JLabel();
        lblNombreUsuario.setText("Nombre usuario:");
        PanelRegistrar.add(lblNombreUsuario, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblContrasenia = new JLabel();
        lblContrasenia.setText("Contraseña:");
        PanelRegistrar.add(lblContrasenia, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnAdministrador = new JRadioButton();
        rbtnAdministrador.setText("Administrador");
        PanelRegistrar.add(rbtnAdministrador, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rbtnAnalista = new JRadioButton();
        rbtnAnalista.setText("Analista");
        PanelRegistrar.add(rbtnAnalista, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtNombreUsuario = new JTextField();
        PanelRegistrar.add(txtNombreUsuario, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtContrasenia = new JPasswordField();
        PanelRegistrar.add(txtContrasenia, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnCrear = new JButton();
        btnCrear.setText("Crear");
        PanelRegistrar.add(btnCrear, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(110, 40), null, 0, false));
        final Spacer spacer1 = new Spacer();
        PanelMain.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelMain;
    }

}
